Vagrant.configure("2") do |config|
  config.vm.define :node1 do |node1|

    node1.vm.box = 'debian/jessie64'
    node1.vm.base_mac = "000000000011"

    node1.vm.provider :virtualbox do |vb|
      vb.memory = '1024'
      vb.cpus = '1'
      vb.gui = 'true'

      vb.customize [
        'modifyvm', :id,
        '--nic1', 'intnet',
        '--intnet1', 'pxe_network',
        '--boot1', 'net',
        '--boot2', 'none',
        '--boot3', 'none',
        '--boot4', 'none'
      ]

    end
  end
end
